### ISSUE TITLE
@ory/kratos typescript API 25.4.0 adds strange "UnknownDefaultOpenApi" von Enums breaking typing

### ISSUE THREAD

**Issue by finsterwalder** [ory/sdk#452]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.com).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.com/l/sign-up-newsletter).

### Describe the bug

I just tried to upgrade @ory/kratos to version 25.4.0.
This produces typing errors in code that worked fine with 1.3.8.
One of the culprits is, that ContinueWithVerificationUi is no longer assignable to ContinueWith.
This is strange.
Digging into it, I found that the ContinueWithVerificationUiActionEnum has a strange definition:

export const ContinueWithVerificationUiActionEnum = {
    ShowVerificationUi: 'show_verification_ui',
    UnknownDefaultOpenApi: '11184809'
} as const;

And there are many more that have "UnknownDefaultOpenApi" things.

Looks like a generation error to me.

Here is the concrete error I get:

error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'ContinueWithVerificationUi' is not assignable to type 'ContinueWith'.
    Type 'ContinueWithVerificationUi' is not assignable to type '{ action: "show_verification_ui"; } & ContinueWithVerificationUi'.
      Type 'ContinueWithVerificationUi' is not assignable to type '{ action: "show_verification_ui"; }'.
        Types of property 'action' are incompatible.
          Type 'ContinueWithVerificationUiActionEnum' is not assignable to type '"show_verification_ui"'.
            Type '"11184809"' is not assignable to type '"show_verification_ui"'.

33 const isContinueWithVerificationUi = (continueWith: ContinueWith): continueWith is ContinueWithVerificationUi => {

### Reproducing the bug

run type checking on my typescript code.

### Relevant log output

```shell

```

### Relevant configuration

```yml

```

### Version

25.4.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
